version: "3"
services:
  geek-time-gin:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: geek-time-gin
    image: geek-time-gin
    ports:
      - "9084:8001"
    restart: always
